# Generated by Django 4.1.5 on 2023-01-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=2000)),
                ("description", models.CharField(max_length=5000)),
                ("question", models.CharField(max_length=1000)),
            ],
        ),
    ]
