# Generated by Django 4.1.5 on 2023-01-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="id",
        ),
        migrations.AddField(
            model_name="registration",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
