# Generated by Django 4.1.5 on 2023-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_remove_registration_id_registration_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                ("discription", models.CharField(max_length=2000)),
            ],
        ),
    ]
