# Generated by Django 4.1.5 on 2023-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_workimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="discription",
        ),
        migrations.AddField(
            model_name="work",
            name="condition",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="work",
            name="documents",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="work",
            name="requirement",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
