# Generated by Django 4.1.5 on 2023-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_work_discription_work_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="condition",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="work",
            name="documents",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="work",
            name="requirement",
            field=models.CharField(max_length=1000),
        ),
    ]
