# Generated by Django 4.1.5 on 2023-04-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_work_condition_alter_work_documents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="email",
            new_name="instagram",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="language",
        ),
    ]
